# Changes here will be overwritten by Copier
_commit: e730ed7
_src_path: gh:audivir/copier-template
author_email: pypi@audivir.de
author_name: Tim Hörmann
description: SQLAlchemy ORM schema for ChEMBL.
github_org: audivir
project_name: chembl-sqlalchemy
project_slug: chembl_sqlalchemy
project_type: python
publishable: true
